Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
ConnectionStrings:
  DefaultConnection: "Host=localhost;Port=5432;Database=test;Username=postgres;Password=B100dy50.waf!"
JwtSettings:
  Secret: "a19b225eb281d6c5e09d0d329aa67fd1"
  Issuer: "YourApp"
  Audience: "YourAppUsers"
  ExpiresInMinutes: 60
AllowedHosts: "*"
