Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Warning
ConnectionStrings:
  DefaultConnection: "Host=localhost;Port=5432;Database=test-2;Username=postgres;Password=B100dy50.waf!"
JwtSettings:
  Secret: "48410ed141fddb6bbcf130f024afe202"
  Issuer: "YourApp"
  Audience: "YourAppUsers"
  ExpiresInMinutes: 60
AllowedHosts: "*"
